### Listar
GET http://localhost:8080/client/tarefa

### Buscar
GET http://localhost:8080/client/tarefa/19

### Incluir
POST http://localhost:8080/client/tarefa
Content-Type: application/json

{
    "nome": "Criada",
    "notas": "com sucesso!",
    "idMae": null,
    "peso": 0,
    "cumprida": false
}

### Alterar
PUT http://localhost:8080/client/tarefa
Content-Type: application/json

{
    "id": 20,
    "nome": "Alterada",
    "notas": "com sucesso!",
    "idMae": null,
    "peso": 9999,
    "cumprida": false
}

### Excluir
DELETE http://localhost:8080/client/tarefa/23
