### Listar
GET http://localhost:8080/api/v1/tarefa

### Buscar
GET http://localhost:8080/api/v1/tarefa/17

### Excluir
DELETE http://localhost:8080/api/v1/tarefa/17

### Alterar
PUT http://localhost:8080/api/v1/tarefa
Content-Type: application/json

{
    "id": 17,
    "nome": "Alterada",
    "notas": "com sucesso!",
    "idMae": null,
    "peso": 9999,
    "cumprida": false
}

### Incluir
POST http://localhost:8080/api/v1/tarefa
Content-Type: application/json

{
    "nome": "Criada",
    "notas": "com sucesso!",
    "idMae": null,
    "peso": 0,
    "cumprida": false
}
