package zcla71.baudoze.planodevida.dto;

import lombok.Data;

@Data
public class Identidade {
	// TODO Para saber o que devo saber, devo primeiro saber quem eu sou:
	//      Se sou católico, devo rezar, ir à missa, confessar-me, ...
	//      Se sou marido, devo reservar tempo para minha esposa, ...
	//      Se sou pai, devo reservar tempo para meus filhos, ...
	//      Se sou filho, devo reservar tempo para meus pais, ...
	//      Se tenho um emprego, devo trabalhar, me capacitar para o trabalho, ...
	//      Se sou humano (🤔), devo fazer exercícios, estudar, dormir, cuidar dos meus bens, ...
	//      E há uma hierarquia de importância entre essas identidades.
	private String nome;
	private String descricao;
}
